name: Recursive
description: A calculator

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_inappwebview: ^5.4.2
  webview_flutter_plus: ^0.3.0+2
  flutter_svg: ^0.18.0
  hexcolor: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/localWeb/
    - assets/localWeb/Images/

